services:
  - type: web
    name: soulspace-frontend
    env: static
    staticSite:
      buildCommand: "cd frontend && npm install && npm run build"
      publishDir: "frontend/build"
      routes:
        - src: "/**"
          dest: "/index.html"
