services:
  - type: web
    name: bluespace
    env: static
    staticPublishDir: frontend/build
    buildCommand: npm run build
    startCommand: npm start
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
