
# render.yaml
services:
  - type: web
    name: SoulSpace
    env: static
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
